---
# tasks file for roles/ansible-role-adauth

- name: Install sssd-client
  ansible.builtin.package:
    name: 
      - adcli
      - sssd-krb5
      - sssd-ldap
      - sssd-common-pac
    state: present

- name: Configure sssd integration with AD
  template:
     src: sssd.conf.j2
     dest: /etc/sssd/sssd.conf
     owner: root
     group: root
     mode: 0600
  notify: restart_sssd

- name: sssd enabled and running
  service:
    name: "{{ sssd_service }}"
    enabled: true
    state: "{{ sssd_service_state }}"

